
name: 'Terraform Test'

on:
  push:
    branches: [ "main" ]
  pull_request:
env:
 ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
 ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
 ARM_SUBSRIPTON_ID: ${{secrets.AZURE_CLIENT_SECRET}}
 ARM_TENANT_ID: ${{secrets.AZRE_TENATNT_ID}}

jobs:
  terraform_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate
