name: 'Terraform Plan and Apply'

on:
  push:
    branches: [ "main" ]
  pull_request:
env:
 ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
 ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
 ARM_SUBSRIPTON_ID: ${{secrets.AZURE_CLIENT_SECRET}}
 ARM_TENANT_ID: ${{secrets.AZRE_TENATNT_ID}}
  

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Generate
      run: terraform plan -out=tfplan 

    - name: Save plan as artifact
      uses: actions/upload-artifact@v4
      with:
          name: terraform-plan
          path: tfplan

  terraform_apply:
    needs: terraform_plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Generate
      run: terraform plan -out=tfplan 

    - name: Save plan as artifact
      uses: actions/download-artifact@v4
      with:
          name: terraform-plan

    - name: Apply Plan
      run: terraform apply -auto-aprove tfplan    